-- =============================================================
-- ETStock Database Schema
-- Generated: 2026-07-07
-- Target: PostgreSQL
-- EF Core migration version: 20260703000000_AddCompanyPhoneNumber
-- =============================================================

-- EF Core migration history table
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"   character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- -------------------------------------------------------------
-- Table: companies
-- -------------------------------------------------------------
CREATE TABLE companies (
    id              integer                 GENERATED BY DEFAULT AS IDENTITY,
    name            text                    NOT NULL,
    address         text                    NOT NULL,
    branch_code     text                    NOT NULL,
    branch_name     text                    NOT NULL,
    invoice_prefix  text                    NOT NULL,
    phone_number    text                    NOT NULL,
    tax_id          text                    NOT NULL,
    vat_rate        numeric                 NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

-- -------------------------------------------------------------
-- Table: monthly_stocks
-- -------------------------------------------------------------
CREATE TABLE monthly_stocks (
    id              integer                 GENERATED BY DEFAULT AS IDENTITY,
    product_name    text                    NOT NULL,
    unit            text                    NOT NULL,
    year            integer                 NOT NULL,
    month           integer                 NOT NULL,
    cost_price      numeric(18,4)           NOT NULL,
    sell_price      numeric(18,4)           NOT NULL,
    opening_qty     numeric(18,4)           NOT NULL,
    buy_qty         numeric(18,4)           NOT NULL,
    sell_full_qty   numeric(18,4)           NOT NULL,
    sell_pos_qty    numeric(18,4)           NOT NULL,
    sales_amount    numeric(18,4)           NOT NULL,
    closing_value   numeric(18,4)           NOT NULL,
    CONSTRAINT pk_monthly_stocks PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_monthly_stocks_year_month_product_name
    ON monthly_stocks (year, month, product_name);

-- -------------------------------------------------------------
-- Table: abbr_invoices
-- -------------------------------------------------------------
CREATE TABLE abbr_invoices (
    id              integer                     GENERATED BY DEFAULT AS IDENTITY,
    invoice_no      text                        NOT NULL,
    invoice_date    timestamp without time zone NOT NULL,
    tax_year        integer                     NOT NULL,
    tax_month       integer                     NOT NULL,
    total_amount    numeric(18,4)               NOT NULL,
    vat_amount      numeric(18,4)               NOT NULL,
    book_no         integer,
    running_no      integer,
    CONSTRAINT pk_abbr_invoices PRIMARY KEY (id)
);

-- -------------------------------------------------------------
-- Table: abbr_invoice_items
-- -------------------------------------------------------------
CREATE TABLE abbr_invoice_items (
    id                  integer         GENERATED BY DEFAULT AS IDENTITY,
    abbr_invoice_id     integer         NOT NULL,
    product_name        text            NOT NULL,
    qty                 numeric         NOT NULL,
    amount              numeric(18,4)   NOT NULL,
    vat_amount          numeric(18,4)   NOT NULL,
    CONSTRAINT pk_abbr_invoice_items PRIMARY KEY (id),
    CONSTRAINT fk_abbr_invoice_items_abbr_invoices_abbr_invoice_id
        FOREIGN KEY (abbr_invoice_id)
        REFERENCES abbr_invoices (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_abbr_invoice_items_abbr_invoice_id
    ON abbr_invoice_items (abbr_invoice_id);
