# lib.ps1 - shared helpers for the ETStock orchestrator scripts.
# Dot-source this: . "$PSScriptRoot\lib.ps1"

$ErrorActionPreference = 'Stop'

# Resolve key paths relative to this script (.orchestrator/scripts/lib.ps1)
$script:OrchDir  = Split-Path -Parent $PSScriptRoot           # .orchestrator
$script:RepoRoot = Split-Path -Parent $script:OrchDir         # repo root
$script:StatePath   = Join-Path $OrchDir 'state.json'
$script:ContextPath = Join-Path $OrchDir 'context.md'
$script:PreamblePath = Join-Path $OrchDir 'prompts\agent-preamble.md'

function Get-State {
    if (-not (Test-Path $script:StatePath)) { throw "state.json not found at $script:StatePath" }
    Get-Content -Raw -Path $script:StatePath | ConvertFrom-Json
}

function Save-State {
    param([Parameter(Mandatory)] $State)
    $State.updatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    $State | ConvertTo-Json -Depth 12 | Set-Content -Path $script:StatePath -Encoding utf8
}

function Test-CleanWorktree {
    $dirty = git -C $script:RepoRoot status --porcelain
    return [string]::IsNullOrWhiteSpace($dirty)
}

function Assert-Tool {
    param([Parameter(Mandatory)][string] $Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required tool '$Name' not found on PATH."
    }
}

# Compose the full prompt handed to a sub-agent CLI.
function Build-AgentPrompt {
    param(
        [Parameter(Mandatory)][string] $Group,
        [Parameter(Mandatory)][string] $Task,
        [Parameter(Mandatory)][string] $Scope,
        [Parameter(Mandatory)][string] $Branch,
        [string] $FeatureId
    )
    $preamble = Get-Content -Raw -Path $script:PreamblePath
    $featLine = if ($FeatureId) { "Feature id: $FeatureId`n" } else { "" }
    @"
$preamble

---

## YOUR TASK ($Group)

${featLine}You are on branch: $Branch

ALLOWED SCOPE (only these paths may be modified):
$Scope

TASK:
$Task

Remember: edit only in-scope files and make the build green with ``dotnet build ETStock.slnx``.
DO NOT run any git command - the orchestrator script will commit, push, and open the PR.
"@
}

# Build a consistent PR body from the task metadata.
function Build-PrBody {
    param(
        [Parameter(Mandatory)][string] $Group,
        [Parameter(Mandatory)][string] $Task,
        [Parameter(Mandatory)][string] $Scope,
        [string] $FeatureId,
        [string] $Agent
    )
    @"
## Task
$Task

## Meta
- Group: **$Group**
- Feature id: $(if ($FeatureId) { $FeatureId } else { '(none)' })
- Allowed scope: ``$Scope``
- Delegated to agent: $Agent

## Review checklist
- [ ] Matches the requirement
- [ ] EF Core / Npgsql pattern (async, DI, parameterized) where applicable
- [ ] MVVM / compiled bindings (x:DataType) where applicable
- [ ] Tests present and passing
- [ ] Changes stay within the allowed scope

> 1 task = 1 PR. Generated by the ETStock orchestrator.
"@
}

# Record a freshly created PR into state.json (task -> PR mapping) and link it
# back to its backlog item when a feature id is given.
function Record-Pr {
    param(
        [Parameter(Mandatory)] $State,
        [Parameter(Mandatory)][string] $Url,
        [Parameter(Mandatory)][string] $Branch,
        [string] $Title,
        [string] $FeatureId
    )
    if ($Url -notmatch '/pull/(\d+)') {
        Write-Warning "Could not parse PR number from URL '$Url' - not recorded."
        return
    }
    $num = $Matches[1]
    $prObj = [pscustomobject]@{
        branch          = $Branch
        feature         = $FeatureId
        title           = $Title
        url             = $Url
        lastReviewedSha = $null
        verdict         = 'pending'
        rounds          = 0
        reviewedAt      = $null
    }
    $State.prs | Add-Member -NotePropertyName $num -NotePropertyValue $prObj -Force

    # Link the backlog item to this PR (task -> PR mapping).
    if ($FeatureId) {
        $item = $State.backlog | Where-Object { $_.id -eq $FeatureId } | Select-Object -First 1
        if ($item) {
            $item.pr     = [int]$num
            $item.branch = $Branch
            $item.status = 'in-review'
        }
    }
    Save-State $State
    Write-Host "Recorded PR #$num in state.json (feature: $(if ($FeatureId) { $FeatureId } else { 'none' }))." -ForegroundColor Green
}

# Map group -> default agent from state.json
function Get-DefaultAgent {
    param([Parameter(Mandatory)][string] $Group)
    $state = Get-State
    $agent = $state.agents.$Group
    if (-not $agent) { throw "No default agent mapped for group '$Group' in state.json" }
    return $agent
}
